export const FETCH_COCKTAILS = 'FETCH_COCKTAILS';
export const POST_COCKTAILS = 'POST_COCKTAILS';

export const FETCH_ONE_COCKTAIL = "FETCH_ONE_COCKTAIL";

export const SAVE_COCKTAIL = "SAVE_COCKTAIL";
export const FETCH_SAVED_COCKTAILS = 'FETCH_SAVED_COCKTAILS';
